/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/planet.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/planet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Planet.geometry} material={materials['Material.002']} rotation={[0, -1.38, 0]} />
      <mesh geometry={nodes.Clouds.geometry} material={nodes.Clouds.material} />
      <mesh geometry={nodes.Atmosphere.geometry} material={nodes.Atmosphere.material} />
    </group>
  )
}

useGLTF.preload('/planet.glb')
