name: Deploy

on:
  push:
    branches:
      - main # Defina a branch na qual deseja que a ação seja executada

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Defina a versão do Node.js que você precisa

    - name: Install dependencies
      run: yarn install

    - name: Run predeploy script
      run: yarn predeploy

    - name: Run deploy script
      run: yarn deploy
